.bumpversion.cfg
pom.xml

Title
-----------
Description
-----------

minor version and whitespace

---

codecov.yml

Title
-----------
Description
-----------

Message codecov

---

pom.xml

Title
-----------
Description
-----------

Show active profile during mvn command

---

serverless.yml

Title
-----------
Description
-----------

make size limit really big

---

code.json
pom.xml
serverless.yml
src/main/java/gov/usgs/wma/waterdata/JsonDataDao.java
src/test/java/gov/usgs/wma/waterdata/JsonDataDaoIT.java

Title
-----------
Description
-----------

end of sprint cleanup

---

Jenkinsfile
package.json
serverless.yml

Title
-----------
Description
-----------

Cloudwatch

---

pom.xml

Title
-----------
Description
-----------

change maven destination

---

pom.xml

Title
-----------
Description
-----------

Artifactory

---

Dockerfile
package.json
serverless.yml

Title
-----------
Description
-----------

use git commit as a tag

---

src/main/java/gov/usgs/wma/waterdata/DetermineRoute.java

Title
-----------
Description
-----------

Also process getTSDescriptions

---

src/test/java/gov/usgs/wma/waterdata/DBTestConfig.java

Title
-----------
Description
-----------

Partitioned table fix

---

.gitignore
Jenkinsfile
package.json
serverless.yml
src/main/java/gov/usgs/wma/waterdata/DetermineRoute.java
src/main/java/gov/usgs/wma/waterdata/JsonData.java
src/main/java/gov/usgs/wma/waterdata/JsonDataRowMapper.java
src/main/resources/application.yml
src/main/resources/sql/jsonData.sql
src/test/java/gov/usgs/wma/waterdata/DetermineRouteTest.java
src/test/java/gov/usgs/wma/waterdata/JsonDataDaoIT.java
src/test/resources/application.yml
src/test/resources/testData/json_data.csv

Title
-----------
Description
-----------

Iow 474 recognize gw discrete data

---

.bumpversion.cfg
code.json
pom.xml

Title
-----------
Description
-----------

update minor version

---

Dockerfile
Jenkinsfile
package.json

Title
-----------
Description
-----------

Serverless update

---

serverless.yml

Title
-----------
Changel log retention to 90 days.
Description
-----------

IOW-638 change log retention to 90 days

---

package.json
pom.xml

Title
-----------
Description
-----------

dependencies

---

.gitignore
Dockerfile
Jenkinsfile
package.json
serverless.yml

Title
-----------
Description
-----------

IOW-651 Added support for delpoying to DEV tier.

---

serverless.yml

Title
-----------
Description
-----------

IOW-699 adjust memory

---

package.json
serverless.yml

Title
-----------
https://internal.cida.usgs.gov/jira/browse/IOW-726
Description
-----------
* Added support for AWS elasticsearch logging

add support elasticsearch logging

---

serverless.yml

Set timeout to 10 seconds.
Title
-----------
Description
-----------

IOW-773 (Adjust aqts-capture lambda timeouts)

---

serverless.yml

Title
-----------
Description
-----------

IOW-781 set reservedConcurrency

---

serverless.yml

Title
-----------
Description
-----------

Added tags

---

serverless.yml

Title
-----------
Description
-----------

changed tag to application_id

---

serverless.yml

This reverts commit 5c8ce41b0adcbba0eefe56cc6bafee289484194a.
Title
-----------
Description
-----------

Revert "IOW-733 (Adjust aqts-capture lambda timeouts)"

---

package.json
serverless.yml

Title
-----------
Description
-----------

IOW-776 use serverless-prune-plugin
